### PR TITLE
chore: repository link for package.json

### PR DESCRIPTION
**Pull request by reslear**

### CODE REVIEW

**Comment by freb97** [comment]
Hello @reslear 👋

Thanks for the contribution! To update the package, you also need to update the package version in the package.json and update the CHANGELOG.md file. I would suggest using the 1.0.2 version.

If you have any questions just message me 😄

**Comment by reslear** [comment]
how do you generate `CHANGELOG.md` ?

**Comment by freb97** [comment]
Currently I just add the new version number manually in the Changelog.md file. In the future I would like it to be automated, but for now that's the workflow...

**Comment by reslear** [comment]
done

**Pull request merged**
